docker/IJulia/Dockerfile
docker/build_sysimg.jl
docker/core/Dockerfile
docker/jimg.jl
docker/julia_v0.3/Dockerfile
docker/mk_user_home.sh
docker/mkjimg.jl
docker/setup_julia.sh
host/nginx/www/assets/js/juliabox.js
host/tornado/src/cloud/aws.py
host/tornado/src/db/user_v2.py
host/tornado/src/handlers/admin.py
host/tornado/src/jbox_container.py
host/tornado/src/jbox_tasks.py
host/tornado/src/vol/jbox_volume.py
host/tornado/src/vol/volmgr.py
host/tornado/www/ipnbadmin.tpl
scripts/install/upload_user_home.py
scripts/run/docker_rmall.sh

This updates Julia version to 0.3.4 and also provides a system image with some packages precompiled into it for faster loading.
Currently only `Gadfly` is precompiled (which also pulls in quite a few other useful packages along as dependencies).
When this version gets applied on to juliabox.org, all users would by default be set to use the system image with precompiled packages. Users may switch back to the default system image from the JuliaBox settings tab.
Also present in the PR are a couple of miscellaneous changes:
- bind zmq socket to internal ip only for security
- updates to default package bundle are applied to test cluster by default to prevent inadvertently applying untested stuff to live cluster.

Julia 0.3.4 update and packages precompiled into custom system image 

---

docker/IJulia/Dockerfile
host/tornado/src/db/accounting_v2.py
host/tornado/src/db/db_base.py
host/tornado/src/jbox_container.py

- Fixed timestamp clash in accounting record insertion. This issue cropped up after the `datetime_to_epoch_secs` was changed to return rounded off values. This adds an option to return milliseconds values, and also retries in case we still get a clash. The table key can be changed along with the next table design iteration to something guaranteed to be unique (session_id + time maybe).
- gfortran and cmake are now part of the base image as they are required to build several packages.

Fix accounting table timestamp clash. Add cmake & gfortran

---

host/tornado/src/cloud/aws.py
host/tornado/src/vol/ebs.py
host/tornado/src/vol/volmgr.py

If an already attached EBS volume is mounted, the mount point was not reported correctly.
The bug was triggered when launching a container for a user with EBS disks failed for
the first time and the user reattempted the login.

fixes for ebs mounts

---

host/tornado/src/jbox.py
scripts/README.md
scripts/install/create_tables_dynamodb.py
scripts/maintain/log_tools.py
scripts/maintain/upload_user_home.py

Given a time range and search pattern, `log_tools.py` searches for events from across multiple cloudwatch logs (groups and streams). Matching events are stored into a single file, sorted by time, instance and source. Useful while tracking events pertaining to a particular user.

script to help troubleshooting with cloudwatch log

---

docker/setup_julia.sh

Per a conversation I had with Viral, this is a request to add [QuantEcon.jl](https://github.com/QuantEcon/QuantEcon.jl) to the list of packages installed by default.

REQUEST: add QuantEcon to default installation

---

docker/IJulia/tutorial/00 - Start Tutorial.ipynb

Changed Shift-Enter to Ctrl-Enter to run cell, without selecting the next cell.

Tutorial start: Use Ctrl-Enter to run cell without selecting next

---

docker/Dockerfile
host/nginx/www/assets/js/juliabox.js
host/tornado/src/cloud/aws.py
host/tornado/src/cloud/awscluster.py
host/tornado/src/db/dynconfig.py
host/tornado/src/db/user_v2.py
host/tornado/src/handlers/admin.py
host/tornado/src/handlers/handler_base.py
host/tornado/src/jbox.py
host/tornado/src/jbox_container.py
host/tornado/src/jbox_tasks.py
host/tornado/src/jboxd.py
host/tornado/src/parallel/__init__.py
host/tornado/src/parallel/user_cluster.py
host/tornado/www/ipnbadmin.tpl

Builds on #237
- Users with cluster privilege can request for and use additional cores (can be regular/spot instances) from JuliaBox settings tab.
- Machines can be connected to via ssh / addprocs using user's JuliaBox ssh key.
- Failed machines are replaced automatically.
- Clusters that are not terminated before logout are auto terminated.
Resource accounting, charging, and a cluster manager to make it easy to connect to the instances will be added in the future.

On demand Julia clusters (machine allocation)

---

docker/Dockerfile
docker/IJulia/tornado/src/fmanage.py
docker/mk_user_home.sh
docker/setup_julia.sh
host/nginx/www/assets/js/juliabox.js
host/tornado/src/juliabox/cloud/aws.py
host/tornado/src/juliabox/plugins/parallel/parallel_handler.py
host/tornado/src/juliabox/plugins/parallel/user_cluster.py
host/tornado/www/ipnbadmin.tpl

Provide Julia nightly:
- Stable version remains as primary version
- Julia nightly with minimal packages also available
- settings console shows Julia versioninfo and package list
Update parallel cluster plugin to create a separate machine file with private IP addresses of the launched instances. Using private IPs may speed up `addprocs`.

Make Julia nightly available. Provide cluster private IPs

---

docker/Dockerfile
docker/IJulia/tornado/src/fmanage.py
docker/mk_user_home.sh
docker/mkjimg.jl
docker/setup_julia.sh
host/tornado/conf/tornado.conf.tpl
host/tornado/src/juliabox/db/dynconfig.py
host/tornado/src/juliabox/jbox_container.py
host/tornado/src/juliabox/plugins/parallel/parallel_handler.py
host/tornado/src/juliabox/plugins/vol_defpkg/__init__.py
host/tornado/src/juliabox/plugins/vol_defpkg/defpkg.py
host/tornado/src/juliabox/vol/jbox_volume.py
host/tornado/src/juliabox/vol/volmgr.py
scripts/maintain/upload_user_home.py

This changes the way JuliaBox bundles Julia packages. Package bundles are now available as a volume plugin.
Containers can now have the following types of volumes mounted, providing:
- home folder
- package bundle
The default plugin implementation has the following behavior:
- package bundle is mounted on to a read-only mount point at `/opt/julia_packages` in the container
- package bundles are now shared across all containers
- package bundles are updated periodically and older bundles are purged
- packages available in the bundle can also be listed from the JuliaBox settings screen
- in future it will be possible to choose between package bundles
Users now can install and maintain their own persistent packages in `~/.julia` folder. User installed packages override default packages.
This …

Persistent packages. Default packages in LOAD_PATH

---

docker/Dockerfile
engine/Dockerfile.daemon
engine/conf/tornado.conf.tpl
engine/src/juliabox/cloud/aws.py
engine/src/juliabox/cloud/awscluster.py
engine/src/juliabox/cloud/awsebsvol.py
engine/src/juliabox/jbox_util.py
engine/src/juliabox/plugins/vol_ebs/ebs.py
engine/src/juliabox/plugins/vol_ebs/ebs_housekeep.py
engine/src/juliabox/srvr_jboxd.py
host/supervisord.conf
scripts/install/aws/clean_instance.sh
scripts/install/aws/configure_cloudwatch_logs.sh
scripts/install/aws/mount_ephemeral.sh
scripts/install/aws/mount_swap.sh
scripts/install/img_create.sh
scripts/install/jbox_configure.sh
scripts/install/sys_install.sh
scripts/jboxcommon.sh
scripts/maintain/upload_user_home.py
scripts/run/clean.sh
scripts/run/docker_rmall.sh
scripts/run/reload.sh
scripts/run/start.sh
scripts/run/stop.sh
webserver/Dockerfile

This fixes EBS volumes broken by #249 by enabling mounting of EBS volumes on host from within a container. The engine daemon prefixes commands related to the `Mount` namespaces with a configurable prefix. The prefix command uses `nsenter` to execute the mount commands in the `mount` namespace of the host init process.
Also simplified scripts used for installation and running, and added helper scripts for managing installation on AWS.

mount EBS volumes from within docker, script changes

---

docker/Dockerfile
engine/Dockerfile.daemon
engine/conf/tornado.conf.tpl
engine/src/juliabox/cloud/awsebsvol.py
engine/src/juliabox/db/user_v2.py
engine/src/juliabox/handlers/handler_base.py
engine/src/juliabox/handlers/main.py
engine/src/juliabox/jbox_container.py
engine/src/juliabox/jbox_tasks.py
engine/src/juliabox/jbox_util.py
engine/src/juliabox/plugins/vol_defpkg/defpkg.py
engine/src/juliabox/plugins/vol_ebs/__init__.py
engine/src/juliabox/plugins/vol_ebs/disk_state_tbl.py
engine/src/juliabox/plugins/vol_ebs/ebs.py
engine/src/juliabox/plugins/vol_ebs/ebs_handler.py
engine/src/juliabox/plugins/vol_ebs/ebs_housekeep.py
engine/src/juliabox/plugins/vol_ebs/vol_ebs_html.tpl
engine/src/juliabox/plugins/vol_loopback/loopback.py
engine/src/juliabox/srvr_jboxd.py
engine/src/juliabox/vol/jbox_volume.py
engine/src/juliabox/vol/volmgr.py
scripts/install/aws/clean_instance.sh
scripts/install/img_create.sh
scripts/install/mount_fs.sh
scripts/install/unmount_fs.sh
webserver/scripts/router.lua
webserver/www/assets/plugins/vol_ebs/vol_ebs.js

EBS volumes often take a long time to mount. There are also multiple steps involved in attaching and mounting it on to a container and a failure in any step makes it difficult to recover cleanly.
This PR changes EBS volumes to be mounted as data volumes only.
- Volumes can be mounted from the JuliaBox configuration tab
- Periodic cleanup tasks monitor aborted/failure situations (often a timeout/user abandoning the session) and can recover from most
Sessions now always get redirected to instances that have a previous container for the same user. This previously relied on cookies and AWS load balancer, and broke unless the user used the same browser the second time. Now re-loading a session with a mounted data volume retains its state.

mount EBS volumes as data volumes, not as user home

---

docker/Dockerfile
engine/conf/tornado.conf.tpl
engine/src/juliabox/cloud/aws.py
engine/src/juliabox/db/__init__.py
engine/src/juliabox/db/container.py
engine/src/juliabox/db/db_base.py
engine/src/juliabox/db/dynconfig.py
engine/src/juliabox/db/user_v2.py
engine/src/juliabox/handlers/admin.py
engine/src/juliabox/jbox_container.py
engine/src/juliabox/plugins/course_homework/course_homework_tbl.py
engine/src/juliabox/plugins/db_dynamodb/__init__.py
engine/src/juliabox/plugins/db_dynamodb/impl_dynamodb.py
engine/src/juliabox/plugins/db_sqlite3/__init__.py
engine/src/juliabox/plugins/db_sqlite3/impl_sqlite3.py
engine/src/juliabox/plugins/usage_accounting/__init__.py
engine/src/juliabox/plugins/usage_accounting/usage_accounting_tbl.py
engine/src/juliabox/plugins/vol_ebs/disk_state_tbl.py
scripts/install/create_tables_dynamodb.py
scripts/install/create_tables_sqlite.py
test/unit_tests.py

Database backend is now pluggable and can be replaced with a different implementation that must provide a few simple CRUD methods. Tables are mostly designed as key-value stores with no requirement of transactions/foreign keys, and are easy to adapt to different backends.
Included are implementations for:
- dynamodb: for deployments on AWS
- sqlite: for local/development setups
Also includes a minor update of Julia to 0.3.11.

replaceable database backend

---

engine/src/juliabox/jbox_util.py
engine/src/juliabox/plugins/auth_zero/zero_auth.py

Check for blanks given as user id and give a nicer error message, instead of throwing an exception.

check for blank user id in zero-auth. fix #264

---

docs/INSTALL.MD
engine/src/juliabox/plugins/vol_hostdisk/__init__.py
engine/src/juliabox/plugins/vol_hostdisk/hostdisk.py
engine/src/juliabox/plugins/vol_loopback/loopback.py
engine/src/juliabox/vol/jbox_volume.py

Particularly useful during development or simple installations.
Mounts a subfolder from the host machine directly as the user home.
All of the host disk space usable by all users of JuliaBox.
JuliaBox user home backups can be optionally disabled, which allows for much
faster startups.
Also updated the installation documents to use this mode for single user / development setup.

volume plugin: shared host machine folder for user home

---

README.md
container/interactive/Dockerfile
engine/src/juliabox/handlers/admin.py
engine/src/juliabox/interactive/sess_container.py
engine/src/juliabox/jbox_container.py
engine/www/ipnbadmin.tpl
webserver/conf/nginx.conf.tpl
webserver/scripts/router.lua
webserver/www/assets/js/juliabox.js

Applications that communicate over HTTP or WebSockets can now
be invoked inside a JuliaBox session and accessed directly from
the browser.
TCP ports 8050-8052 from the container are proxied through a
user chosen alias over https://juliabox.org/jcw_<alias>/ (as websockets) or
as https://juliabox.org/jci_<alias>/ (as plain HTTP). The ports can be
opened and mapped to an alias from the JuliaBox settings tab.
JuliaBox plugins can also open ports transparently and provide a convenient
and seamless experience. Widely used applications may provide such plugins.

make HTTP/WebSocket applications accessible

---

engine/src/juliabox/plugins/api_admin/api.py
engine/src/juliabox/plugins/api_admin/api_admin.tpl
webserver/www/assets/plugins/api_admin/api_admin.js

This allows users to opt in for API publishing on their own. At this point there's no need to restrict API publishing access.

allow users to opt in for API publishing

---

container/interactive/setup_julia.sh
docs/INSTALL.MD

Fix missing whitespace in bash command that breaks script - #283
Docker installs itself with gid 999 on most systems. But installation breaks if it is not, and needs a change in Dockefile. Mentioned this in the installation document.

fix setup script. mention docker gid configuration

---

container/api/Dockerfile
container/interactive/Dockerfile
container/interactive/mk_user_home.sh
engine/src/juliabox/handlers/admin.py
engine/src/juliabox/vol/volmgr.py
engine/www/ipnbadmin.tpl
webserver/www/assets/js/juliabox.js

Update Julia 0.4 to the rc1 release.
And, do not precompile packages on Julia v0.3 anymore. Now that we have Julia v0.4 in a good shape with a much better precompilation model, we can stop what we have been doing on Julia v0.3.
It will avoid JuliaBox needing to touch the user's bashrc script and ipython profiles, which are problamatic when user disk is nearly full. Also, precompilation has been randomly problamatic recently. See #292

update to Julia v0.4.0-rc1, discontinue precompilation on v0.3

---

container/interactive/setup_julia.sh

As of v0.2.0, Interact is compatible with IPython >= 3.0.
Is there any other reason to stay on master?

Remove checkout of Interact.jl

---

container/api/Dockerfile
container/interactive/Dockerfile
container/interactive/IJulia/ipython_notebook_config.py
container/interactive/IJulia/tornado/src/fmanage.py
container/interactive/mk_user_home.sh
container/interactive/setup_julia.sh
engine/src/juliabox/vol/jbox_volume.py
engine/www/ipnbadmin.tpl
webserver/www/assets/js/juliabox.js

- update Julia 0.4.0-rc2 to 0.4.0
- add Julia 0.5.0-dev
- add message explaining conflict between system provided and user installed packages
- provide button fix conflicts by deleting user installed packages (actually by renaming .julia)
- increase Jupyter `KernelRestarter.time_to_dead` from 3 to 6
Failure to start notebooks are most certainly due to package conflicts. The only way to resolve them is to update local packages to acceptable versions. There's a button in the settings page now to rename `~/.julia` to a temporary folder which should resolve this issue for most cases.
Jupyter restarts the kernel when it fails to start. There's a check to prevent endless restarts, but that kicks in only if kernel restarts in less than 3 secs. That's too small in some cases and causes IJulia to …

update Julia version, packages & package handling

---

engine/conf/tornado.conf.tpl
engine/src/juliabox/srvr_jbox.py

Cluster leader updates a S3 hosted static page on each maintenance cycle (once in 5 minutes).
Reports load for all active machines in cluster, and any dead nodes.
Dead machines should be automatically removed and replaced with new ones.
JuliaBox status can be considered as not green if any of the following is true:
- status not updated for more than 10 minutes
- machines consistently appear dead
- status page itself is not accessible (indicating Amazon S3 is not accessible)
- AWS status page shows disruptions
fixes #304

simple status page hosted on S3

---

container/interactive/Dockerfile
engine/conf/tornado.conf.tpl
engine/src/juliabox/api/api_container.py
engine/src/juliabox/interactive/sess_container.py

This provides a way to control system rlimits on user processes running inside docker container.
Dockerfile sets the hard limit, systemwide `.juliarc` sets limits for IJulia and commandline `julia`, and systemwide `.bashrc` sets limits for shellinabox.

ulimits for docker container, shellinabox, Julia

---

docs/INSTALL.MD
engine/src/juliabox/plugins/compute_ec2/impl_ec2.py
engine/src/juliabox/srvr_jboxd.py

- reduce idle instance time to 50 minutes
- tweak load distribution to tighten machine allocation, prevent thrashing
- refresh disks and packages on a daemon restart (since unlike a fresh start, this will not be triggered by container managers)
- mention in the installation document that a single node setup requires a FQDN when it's not `localhost` (for websockets. ref: #14)

tweaks for load distribution, error recovery, installation instructions

---

container/api/Dockerfile
container/interactive/Dockerfile
container/interactive/setup_julia.sh
engine/Dockerfile.base
engine/src/juliabox/srvr_jbox.py

- update to Julia 0.4.2.
- `cli53` library is now pulled out. Excluded from dockerfile and not used internally anymore.
- do not build cloned packages, as build throws errors and occasionally segfaults.
- disable httpclient cert check (include cacerts in future)

Julia update and other fixes

---

container/interactive/IJulia/tutorial/Calling C and Python.ipynb

Fixed typo in text above In[8]: missing "can".

Fix Typo in Calling C and Python.ipynb

---

container/interactive/IJulia/tutorial/Calling C and Python.ipynb

There is a typo in the tutorial file, Calling C and Python, section ## Calling Matplotlib:
" ... we had to monkey-patch Matplotlib to intercept its drawing commands [] queue the figure for rendering ... "
I'm not sure if it should be "and", "to", "in order to" or something else. I'd love feedback from a reviewer! :)

Fixed typo in Calling C and Python ##Matplotlib

---

container/interactive/mk_user_home.sh
engine/src/juliabox/plugins/bucket_gs/impl_gs.py
engine/src/juliabox/plugins/bucket_gs/info.md
engine/src/juliabox/plugins/db_cloudsql/__init__.py
engine/src/juliabox/plugins/db_cloudsql/info.md
host/supervisord.conf
scripts/install/create_tables_cloudsql.py
scripts/install/img_create.sh
scripts/install/sys_install.sh

Running `cloud_sql_proxy` as a process outside docker because the docker instance `cloud_sql_proxy` was being removed by `backup_and_cleanup`. (+ other minor fixes)

Fixes for google plugins

---

engine/src/juliabox/plugins/compute_gce/impl_gce.py

Use WHERE clause instead of LOCK command to prevent race condition while adding new instances.

Use where clause while updating last scale up time instead of locks

---

engine/src/juliabox/handlers/handler_base.py

* Post authentication plugins must have a method `process_user_id`.
* This method returns a Boolean indicating whether a user is allowed to pass after authentication.

Support for post auth plugins

---

engine/src/juliabox/jbox_util.py
engine/src/juliabox/plugins/bucket_gs/impl_gs.py
engine/src/juliabox/plugins/compute_gce/impl_gce.py
engine/src/juliabox/plugins/dns_gcd/impl_gcd.py
scripts/install/gce/configure_metrics.py
scripts/run/gce/logger_daemon.py
scripts/run/gce/logs_downloader.py

Replaced the `@retry_on_bsl` decorator with `@retry_on_errors`, which considers more errors and uses exponential back-off.
This helps prevent 404 and 5xx errors that happen occasionally.
As in #384 the `max_sleep_time` of 32 seconds may be too large.

retry decorator for google plugins

---

engine/src/juliabox/db/api_spec.py
engine/src/juliabox/db/db_base.py
engine/src/juliabox/db/dynconfig.py

The size of the `value` field in `jbox_dynconfig` table was limited to 200 characters by `VARCHAR(200)`.   This was causing truncation and hence JSON parse error.  Changed it to `TEXT` which can be 65536 characters long.
Did the same for `cmd` field of `jbox_apispec`.

Fix truncation of `value` field of dynconfig table when using Cloudsql

---

engine/src/juliabox/handlers/handler_base.py

The method `get_ports` was returning Null for deleted containers in `is_valid_req` resulting in `KeyError`.
Fixed with Null check and also checked for the required keys.

Check for Null/invalid ports data in `is_valid_req`

---

docs/Architecture.md
engine/src/juliabox/cloud/compute.py
engine/src/juliabox/plugins/compute_ec2/impl_ec2.py
engine/src/juliabox/plugins/compute_gce/impl_gce.py
engine/src/juliabox/plugins/compute_singlenode/impl_singlenode.py
engine/src/juliabox/srvr_jboxd.py

Implemented a method `publish_stats_multi` in google compute plugin.  This takes a list of metrics to be uploaded in a single API call.  Made changes appropriately in other compute plugins and in `publish_perf_counters` method of `JBoxd`.
This will prevent the monitoring API from being called too many times in a small interval of time.

Upload multiple metrics in a single API call in google monitoring

---

engine/src/juliabox/plugins/compute_gce/impl_gce.py

Since load monitoring metric upload requests are serviced in parallel, it looks like metrics with earlier time-stamps are sometimes sent to the cloud monitoring service after metrics with later time-stamps have been uploaded.
This is not allowed by Google Cloud Monitoring version 2 causing an error and the metrics are lost.
In this fix, we catch such a failure, sleep for one second and retry with the current time-stamp.
The issue can be reproduced by triggering scaling, by loading the cluster with enough user sessions.  The metrics are successfully uploaded with this fix.

Fix bug in timeseries upload

---

engine/src/juliabox/jbox_util.py
engine/src/juliabox/plugins/db_cloudsql/impl_cloudsql.py

It was observed that `OperationalError: (2006, 'MySQL server has gone away')` was thrown when connections went stale due to idle timeout when calling the execute method on a cursor.
Added a wrapper for execute in `JBoxCloudSQL` that catches this error and retries with a new connection.

Reconnect to MySQL on OperationalError

---

engine/src/juliabox/plugins/compute_ec2/impl_ec2.py

Occurs when load value of one of the instances in the cluster is fetched as `None`. Most likely for `self` instance, when request lands on an instance before it got a change to initialize it's own load value.
Ref exception stack
````
File "/jboxengine/src/juliabox/plugins/auth_google/google_auth.py", line 99, in get
self.post_auth_launch_container(user_id)
File "/jboxengine/src/juliabox/handlers/handler_base.py", line 434, in post_auth_launch_container
if self.try_launch_container(user_id, max_hop=False):
File "/jboxengine/src/juliabox/handlers/handler_base.py", line 342, in try_launch_container
if ((cont is None) or (not cont.is_running())) and (not Compute.should_accept_session(is_leader)):
File "/jboxengine/src/juliabox/cloud/compute.py", line 165, in should_accept_session
return …
```

fix sum with None exception

---

engine/src/juliabox/cloud/compute.py
engine/src/juliabox/plugins/db_cloudsql/impl_cloudsql.py
engine/src/juliabox/vol/jbox_volume.py
scripts/install/create_tables_cloudsql.py

Migration plugins should provide two methods:
- `pull_from_bucketstore(backup_location):` Downloads user backup from the desired bucket and platform.
- `should_migrate(user_id):` Return `True` if user has been marked for migration, else `False`.
If a migration plugin is enabled and the user has been marked for migration, then the `pull_from_bucketstore` method of the plugin is used to download the user backup on login. Else, the default bucket plugin is used via `JBoxVol.pull_from_bucketstore`.

Support for migration plugins

---

engine/src/juliabox/plugins/vol_defpkg/defpkg.py

Package bundles do not get initialized occasionally, likely due to a race condition in the triggering message sent from `jbox` to `jboxd`. This is not a problem when the installation has them configured and updated separately. But logins fail on a single node or static cluster when this occurs. This fix is to check and initialize package bundles before using.
fixes #392

initialize package bundle if not done

---

engine/src/juliabox/db/__init__.py
engine/src/juliabox/handlers/main.py
engine/src/juliabox/interactive/sess_container.py
engine/src/juliabox/srvr_jboxd.py
webserver/scripts/router.lua

- Restart container if it fails to start properly. Occasionally the docker container fails to respond to the exposed ports. Now we attempt to resuscitate the container if it fails to start properly.
- Starting the first session on a fresh instance sometimes times out, because of warming up overhead. Increase startup timeout.
- When both API and interactive sessions are co-located, both may try to elect the instance as cluster leader at the same time. That would result in a concurrent update error. Not fatal, but good to have it handled.

fix a few session startup issues

---

engine/src/juliabox/api/api_container.py
engine/src/juliabox/db/__init__.py
engine/src/juliabox/db/container.py
engine/src/juliabox/db/db_base.py
engine/src/juliabox/db/dynconfig.py
engine/src/juliabox/db/instance.py
engine/src/juliabox/handlers/admin.py
engine/src/juliabox/handlers/api_info.py
engine/src/juliabox/handlers/handler_base.py
engine/src/juliabox/interactive/sess_container.py
engine/src/juliabox/jbox_tasks.py
engine/src/juliabox/plugins/compute_ec2/impl_ec2.py
engine/src/juliabox/plugins/parallel/parallel_housekeep.py
engine/src/juliabox/plugins/vol_ebs/ebs.py
engine/src/juliabox/plugins/vol_ebs/ebs_housekeep.py
engine/src/juliabox/srvr_jbox.py
engine/src/juliabox/srvr_jboxd.py
scripts/install/create_tables_cloudsql.py
scripts/install/create_tables_dynamodb.py
scripts/install/create_tables_sqlite.py
test/unit_tests.py

Helps scaling JuliaBox up to a large number of machines.
Necessary when configured for dedicated machines instead of shared.
- Individual instances publish session data to `jbox_session` table. Instead of RPC calls to all instances,
- query `jbox_session` to get logged in instance of a user 
- scan `jbox_session` to list active sessions
- Maintain instance statistics in a new table (`jbox_instance`) instead of querying individual instances.
- Change compute_ec2 plugin to use `jbox_instance` table to reduce api calls and avoid iterating through / querying all instances.
Tested with a large static cluster. For an auto scaling cluster, scale down and instance allocation logic will need small changes on similar lines.

scale to large number of instances

---

engine/src/juliabox/plugins/db_cloudsql/impl_cloudsql.py
scripts/install/create_tables_cloudsql.py

Quote all identifiers in MySQL statements to prevent clashes with keywords.

Quote all identifiers in cloudsql statements

---

engine/src/juliabox/cloud/compute.py
engine/src/juliabox/plugins/compute_ec2/impl_ec2.py

Move fixed scaling logic from `compute_gce` plugin to common code in `compute.py`

Move fixed scaling logic to common code

---

scripts/run/gce/logger_daemon.py

If an error occurs and the logger restarts, the old file handles are lost.  This causes all the logs starting from time=0 to be uploaded at once.  The size limit for uploading logs is 10MB, so this error will happen repeatedly.
Prevent this by ignoring 400 status associated with this error.

Ignore 400 errors when uploading logs

---

webserver/www/assets/html/wsocktest.html

fixes #413
Browsers now throw the uncatchable security exception when a secure page attempts non-secure websocket connection.
This change detects the current page protocol and switches websocket protocol accordingly.

detect protocol before testing websocket conn

---

container/interactive/IJulia/tornado/src/fmanage.py
webserver/www/assets/js/juliabox.js

Git clone is allowed only when the destination path does not exist or is an empty folder.
Fails with an indicative error message otherwise.
fixes #375

git clone warns and does not delete existing files

---

engine/src/juliabox/db/instance.py

Remove cluster name from instance name when returning list of stale instances to prevent qualifier from being added twice by calling functions.

Fix qualifier in purge_stale_instances

---

engine/src/juliabox/handlers/admin.py

Fix missing argument to `get_active_sessions`.

Fix argument to get_active_sessions

---

engine/conf/tornado.conf.tpl
engine/src/juliabox/handlers/handler_base.py
engine/src/juliabox/plugins/auth_github/__init__.py
engine/src/juliabox/plugins/auth_github/github_auth.py
engine/src/juliabox/plugins/auth_github/github_login_btn.tpl

fixes #247
- register application with GitHub (as described in https://developer.github.com/v3/oauth/)
- use `juliabox.plugins.auth_github` as plugin
- specify github client id and secret in `github_oauth` section, e.g.: `"github_oauth": { "key": "<client id>", "secret": "<secret>" }`

add GitHub OAuth2 authentication plugin

---

engine/src/juliabox/db/user_v2.py

`JBoxDB.VCHAR` is too short to hold the google token.  Hence changing it to `JBoxDB.TEXT`.

Change gtok type to TEXT in cloudsql

---

engine/src/juliabox/vol/jbox_volume.py

Use the `-H` option for `df` to get the size in MB.

Show disk usage in MB instead of MiB Ref: #419

---

engine/src/juliabox/db/__init__.py
engine/src/juliabox/db/api_spec.py
engine/src/juliabox/db/container.py
engine/src/juliabox/db/dynconfig.py
engine/src/juliabox/db/instance.py
engine/src/juliabox/db/user_profile.py
engine/src/juliabox/db/user_v2.py
engine/src/juliabox/handlers/handler_base.py
engine/src/juliabox/plugins/auth_github/github_auth.py
engine/src/juliabox/plugins/auth_google/google_auth.py
engine/src/juliabox/plugins/auth_linkedin/linkedin_auth.py
engine/src/juliabox/plugins/site_redirect/impl_site_redirect.py
scripts/install/create_tables_cloudsql.py
scripts/install/create_tables_dynamodb.py
scripts/install/create_tables_sqlite.py

Add user_profiles table, auto fill by auth modules.
The profile table stores a few attributes to use while communicating with users. Authentication modules fill attributes if they are available to them as part of the login response. A record is maintained to indicate the source of each attribute that was populated automatically.
If users are allowed to explicitly set their profile in the future, authentication modules will not overwrite the values set by users.
This also includes a minor change to the AWS index specification to handle a boto API change.

add user profile table

---

scripts/install/create_tables_cloudsql.py

Some fixes in index creation in `create_tables_cloudsql.py`:
* For each index check if it exists, if not create.
* Separate index creation from table creation.

Create indexes if not created

---

engine/src/juliabox/plugins/auth_github/github_auth.py

If user has not made email public in GitHub profile then login is not possible.  Show an error asking user to make email public.

Show error page if email is not available when using GitHub Auth

---

engine/src/juliabox/plugins/auth_github/github_auth.py
engine/src/juliabox/plugins/db_cloudsql/impl_cloudsql.py

The python package `MySQLdb` uses `latin-1` charset by default.  Changing charset to `utf-8`.

Set charset to utf-8 in cloudsql

---

engine/src/juliabox/srvr_jboxd.py

Check whether `sessname` is `None` before passing to `attach_instance`.

Check for deleted containers before saving session props

---

engine/src/juliabox/plugins/auth_github/github_auth.py
engine/src/juliabox/plugins/auth_google/google_auth.py
engine/src/juliabox/plugins/auth_linkedin/linkedin_auth.py

Catch errors that occur when updating profile.  Print the traceback.

Prevent login failures due to profile update errors

---

container/interactive/IJulia/tornado/www/upload.tpl

Change event from `complete` to `queuecomplete`.  This event is triggered only after all files are uploaded.

Reload page only after all files are uploaded

---

engine/src/juliabox/plugins/auth_github/github_auth.py

Log response when `access_token` is missing in GitHub authentication response.  Show appropriate error message.

Log response when access token is missing, show appropriate error message

---

engine/src/juliabox/plugins/auth_github/github_auth.py
engine/src/juliabox/plugins/auth_google/google_auth.py

This lets us log the response object when an error occurs during OAuth.  With `GoogleOAuth2Mixin` the response is handled by the library and not accessible to us.
Tested login and google drive.

Extend OAuth2Mixin instead of GoogleOAuth2Mixin in google auth plugin for better access to debugging information.

---

engine/src/juliabox/handlers/handler_base.py
engine/src/juliabox/jbox_util.py
engine/src/juliabox/plugins/auth_github/github_auth.py
engine/src/juliabox/plugins/auth_linkedin/linkedin_auth.py

Generate a secret string from a secret provided in `jbox.user` and a randomly generated string.  This is saved in the client cookie and checked with the response from the OAuth request.
Added this feature to GitHub and LinkedIn authentication plugins.

Add a state parameter in oauth for better security

---

engine/src/juliabox/plugins/bucket_gs/impl_gs.py

Changed the chunk size from 4 MB to 64 MB.
Downloaded a file of size ~ 300 MB to a GCE instance from a bucket 10 times asynchronously.
|Chunk size (MB)|Average time taken (s)|
|-----------------------|------------------------------|
|4|16.73|
|64|3.94|
Did not observe significant changes in download time beyond 64 MB and below 4 MB.
|Chunk size (MB)|Average time taken (s)|
|-----------------------|------------------------------|
|4|9.37|
|64|4.29|

Increase chunk size in Google Storage plugin

---

engine/src/juliabox/plugins/compute_gce/impl_gce.py

This is necessary to keep standby instances from getting killed.

Let scaling plugin decide whether to terminate instance

---

engine/www/ipnbsess.tpl
webserver/www/assets/js/juliabox.js

This will accommodate for up to 10 minutes of ping failures.

Increase ping interval to 1 minute and retries to 10

---

webserver/www/assets/js/juliabox.js

The cookies will remain behind if the user does not dismiss the timeout alert and reloads the page.  This will cause invalid ping requests and render the session unusable.

Delete cookies on timeout before showing the logout dialog
