JuliaCloud/JuliaBox

- docker/IJulia/Dockerfile
- docker/julia_v0.3/Dockerfile
- docker/setup_julia.sh
- host/tornado/www/ipnbadmin.tpl
- update Julia version to 0.3.5
- added MAT.jl
- added binaries required for Nemo.jl
> update julia version and packages

- docker/IJulia/Dockerfile
- host/tornado/src/cloud/aws.py
- host/tornado/src/db/disk_state.py
- host/tornado/src/handlers/auth.py
- host/tornado/src/handlers/main.py
- host/tornado/src/handlers/ping.py
- host/tornado/src/jbox.py
- host/tornado/src/jbox_container.py
- host/tornado/src/jbox_util.py
- host/tornado/src/jboxd.py
Logging changes are for easier scripting on log data (uploaded on to cloudwatch).
SymPy version updated as discussed in #196
> Logging improvements. Update sympy version

- docker/IJulia/tutorial/Metaprogramming.ipynb
I edited this directly in the ipynb source file, hopefully that doesn't mess anything up.
> Minor typo in tutorial/Metaprogramming.ipynb

- host/tornado/src/jbox.py
- host/tornado/src/jbox_container.py
- host/tornado/src/vol/ebs.py
- host/tornado/src/vol/jbox_volume.py
- host/tornado/src/vol/volmgr.py
- scripts/maintain/disk_tools.py
- generate ssh keys and gitconfig if they are not found
- handle restore of disk haveing folders without write access
- maintenance script updates
- allow logins even if there was not enough space for JuliaBox to update/create configuration files (this change is still incomplete as the user needs to be intimated to free up some space)
> Multiple enhancements and fixes

- docker/setup_julia.sh
- host/nginx/conf/nginx.conf.tpl
- host/nginx/www/assets/js/juliabox.js
- host/tornado/src/db/__init__.py
- host/tornado/src/db/course_homework.py
- host/tornado/src/db/dynconfig.py
- host/tornado/src/db/user_v2.py
- host/tornado/src/handlers/__init__.py
- host/tornado/src/handlers/course_homework.py
- host/tornado/src/jbox.py
- scripts/install/create_tables_dynamodb.py
- scripts/maintain/upload_homework.py
Limited functionality as of now:
- can only evaluate results that are exact matches
- unlimited number of attempts (so multiple choice questions may not be appropriate yet)
- scripts to upload answers into the system and download evaluation results need admin access
Future changes will separate out the evaluation process into a Julia based service (instead of the current python based one) which will allow for more complex matching and add/improve the user interface.
> Preliminary support for evaluating answers for notebook based assignments

- docker/setup_julia.sh
- host/nginx/www/assets/js/juliabox.js
- host/tornado/src/db/course_homework.py
- host/tornado/src/handlers/course_homework.py
- scripts/maintain/homework.py
- scripts/maintain/upload_homework.py
APIs to be invoked in the context of the course creator/administrator:
- create/update a course by providing json spec (example: upload_homework.py)
- fetch answers configured
- fetch evaluations
APIs invoked in the student's context:
- evaluate/record answer for a question
> APIs for homework creation/evaluation

- host/tornado/src/db/course_homework.py
- fix score to be float type in `get_answer`
- do conversion to `Decimal` for dynamodb
- also return `max_score` while giving out self score
> fix for homework scoring

- docker/IJulia/Dockerfile
- docker/IJulia/custom.js
- docker/julia_v0.3/Dockerfile
- docker/setup_julia.sh
- host/tornado/src/cloud/aws.py
- host/tornado/src/handlers/course_homework.py
- host/tornado/www/ipnbadmin.tpl
- scripts/install/img_create.sh
- update Julia version
- add MixedModels package
- restore IJulia notebook icon
- make homework report api provide self scores when called by regular users (only admins or courseowners had access to it earlier which returned scored for all participants)
> update Julia, add MixedModels

- docker/Dockerfile
- docker/mk_user_home.sh
- docker/setup_julia.sh
- host/tornado/src/vol/jbox_volume.py
- also link julia to /usr/bin
- rename JuliaBox.jl to JuliaWebAPI.jl
> use IJulia generated kernel

- docker/setup_julia.sh
- host/nginx/www/assets/plugins/course_homework/course_homework.js
- host/nginx/www/assets/plugins/parallel/parallel.js
- host/tornado/src/juliabox/db/user_v2.py
- host/tornado/src/juliabox/plugins/parallel/parallel_housekeep.py
- host/tornado/src/juliabox/plugins/vol_ebs/ebs_housekeep.py
- host/tornado/src/juliabox/vol/jbox_volume.py
Include JuliaBoxUtils.jl into default packages, which will contain useful utility functions.
Also:
- added missing js files for JuliaBox provided plugins
- added missing annotations for housekeeping methods for plugins
- update kernel to 0.3.9
> add JuliaBoxUtils.jl. few fixes for #240

- host/tornado/conf/tornado.conf.tpl
- host/tornado/src/juliabox/cloud/aws.py
- host/tornado/src/juliabox/plugins/parallel/parallel_handler.py
- host/tornado/src/juliabox/plugins/parallel/user_cluster.py
- host/tornado/src/juliabox/plugins/parallel/user_cluster_html.tpl
- scripts/install/mount_fs.sh
- increase default disk space
- increase inode count
- changes to parallel plugin (to speed up connections and fix ui)
> disk space and parallel fixes

- scripts/install/create_tables_dynamodb.py
- scripts/install/create_tables_sqlite.py
- scripts/maintain/disk_tools.py
- scripts/maintain/homework.py
- scripts/maintain/upload_user_home.py
@tanmaykm, I have, as you suggested, added the path to the Python module manually in each script that runs on the host. I have not removed the ```env``` dependence in this PR as I am not familiar enough with the codebase to be sure I won't break anything.
> Add JuliaBox Python module to path in scripts, fix #261.

- docs/INSTALL.MD
I will push commits here as I add (what I hope is) useful information to the installation documentation. @tanmaykm, please comment/review as necessary.
> Add more detail to installation documentation

- engine/conf/tornado.conf.tpl
- engine/src/juliabox/plugins/db_sqlite3/impl_sqlite3.py
- engine/src/juliabox/plugins/user_admin/__init__.py
- engine/src/juliabox/plugins/user_admin/user_admin.py
- engine/src/juliabox/plugins/user_admin/user_admin.tpl
- webserver/www/assets/plugins/user_admin/user_admin.js
Helps an administrator provision users and allocate/de-allocate resources with validation.
> user administration

- engine/src/juliabox/plugins/db_sqlite3/impl_sqlite3.py
- handle Decimal types
- handle more than 1 primary keys
> sqlite plugin changes

- container/api/Dockerfile
- container/interactive/Dockerfile
- engine/src/juliabox/plugins/compute_ec2/impl_ec2.py
- update Julia v0.4.0 to rc2
- updated all other Linux packages (primarily for the latest ZMQ package)
- tweaked nginx routing to handle condition when one scaling event brings up more than 1 instance
> update Julia v0.4.0 to rc2, update base linux packages

- engine/src/juliabox/plugins/vol_defpkg/defpkg.py
- engine/src/juliabox/plugins/vol_hostdisk/hostdisk.py
- engine/src/juliabox/plugins/vol_loopback/loopback.py
- engine/src/juliabox/vol/jbox_volume.py
Changes to handle the new response JSON format sent by docker 1.8.3 for `docker inspect`.
> handle changed docker inspect json format

- engine/src/juliabox/plugins/course_homework/course_homework.py
send back exception trace, instead of letting out a server error
> catch exceptions while creating homework courses

- container/interactive/Dockerfile
- container/interactive/setup_julia.sh
About CloudArray: https://github.com/gsd-ufal/cloudarray.jl
> Added required packages to use CloudArray

- container/interactive/Dockerfile
add default packages to LOAD_CACHE_PATH
> enable precompiled cache for default packages

- docs/INSTALL.MD
Clarifications regarding issue #342
> Small clarifications in install docs

- scripts/maintain/disk_tools.py
Get storage plugin from `JBPluginCloud.jbox_get_plugin(JBPluginCloud.JBP_BUCKETSTORE)` instead of using `JBoxS3`
> Get storage plugin from factory method instead of hard-coding S3 plugin in disk_tools.py

- engine/src/juliabox/cloud/compute.py
- engine/src/juliabox/plugins/bucket_gs/__init__.py
- engine/src/juliabox/plugins/bucket_gs/impl_gs.py
- engine/src/juliabox/plugins/bucket_gs/info.md
> Added Google Cloud Storage plugin

- engine/Dockerfile.base
- engine/src/juliabox/db/api_spec.py
- engine/src/juliabox/db/container.py
- engine/src/juliabox/db/db_base.py
- engine/src/juliabox/db/dynconfig.py
- engine/src/juliabox/db/user_v2.py
- engine/src/juliabox/plugins/course_homework/course_homework_tbl.py
- engine/src/juliabox/plugins/db_cloudsql/__init__.py
- engine/src/juliabox/plugins/db_cloudsql/impl_cloudsql.py
- engine/src/juliabox/plugins/db_cloudsql/info.md
- host/supervisord.conf
- scripts/install/create_tables_cloudsql.py
- scripts/install/sys_install.sh
* All APIs of `JBoxCloudSQL` class unit-tested.
* Partially tested with running JuliaBox instance.
* Setup instructions in info.md
> Added google CloudSQL plugin

- engine/src/juliabox/jbox_util.py
- engine/src/juliabox/plugins/bucket_gs/impl_gs.py
- engine/src/juliabox/plugins/dns_gcd/__init__.py
- engine/src/juliabox/plugins/dns_gcd/impl_gcd.py
This PR contains:
* Google DNS plugin
* Fix bugs in google storage plugin
> Google DNS plugin

- host/supervisord.conf
- scripts/install/gce/configure_metrics.py
- scripts/run/gce/logger_daemon.py
This PR contains:
* A daemon for uploading logs from local files to google cloud logging
* A script to setup the Cloud Monitoring metrics
> Added logger daemon and configure metrics script for google cloud

- engine/src/juliabox/cloud/compute.py
- engine/src/juliabox/plugins/compute_gce/__init__.py
- engine/src/juliabox/plugins/compute_gce/impl_gce.py
- scripts/install/create_tables_cloudsql.py
- scripts/install/gce/configure_metrics.py
Test was done for the following behaviour:
1)  When average load exceeds 80%, instances are added and scale down happens when avg load is below 80%.
2)  When leader is killed, other instances elect new leader.
3)  When instance with an image of higher version is added to the autoscale group, it becomes the new leader.
> Added google compute plugin

- engine/src/juliabox/plugins/compute_gce/impl_gce.py
Missed a call to commit in the last PR #377 .  Without this future updates get blocked.
> Fix scale up: Commit update transaction

- engine/src/juliabox/cloud/compute.py
- engine/src/juliabox/plugins/sendmail_smtp/__init__.py
- engine/src/juliabox/plugins/sendmail_smtp/impl_smtp.py
- engine/src/juliabox/plugins/sendmail_smtp/info.md
- scripts/install/create_tables_cloudsql.py
A plugin to send mails using python smtplib.  
The sender, recipient and timestamp of emails is stored in a table in Google Cloud SQL.  This is used in the method `get_email_rates`  to get the number of mails sent in the last 24 hours .
> Added SMTP plugin

- engine/src/juliabox/plugins/sendmail_smtp/__init__.py
- engine/src/juliabox/plugins/sendmail_smtp/impl_smtp.py
Fix some coding issues in sendmail_smtp plugin.
> Fix bugs in smtp plugin

- scripts/run/gce/logger_daemon.py
- scripts/run/gce/logs_downloader.py
* Modified the log uploader script to label logs by file name (ex. enginedaemon.log, engineinteractive.log etc).
* Added a download script that downloads logs between two given datetimes.
* The downloader groups log files in folders by instance name.
> Logs downloader for google backend

- engine/src/juliabox/plugins/bucket_gs/impl_gs.py
- engine/src/juliabox/plugins/compute_gce/impl_gce.py
- engine/src/juliabox/plugins/dns_gcd/impl_gcd.py
The connection objects returned by the `build` function of `googleapiclient.discovery` are not thread safe.  Using the `threading` module, I have made all connection objects local to a thread.
An `SSL3_GET_RECORD: wrong version number` is seen due to this issue.  This happens when a connection is established to a service by one thread and used by another thread.  This issue can be reproduced by logging out several user sessions at once causing `backup_and_cleanup` jobs to be queued which uploads files to Google Cloud Storage (if using `bucket_gs` plugin).  Some of the uploads should fail with the above mentioned error.
Ran a script that logs in several `auth_zero` users.  Issue was seen when idle time out happened and `backup_and_cleanup` was called.
Backup is successful and there are no …
> Have thread local connection objects to Google services

- engine/src/juliabox/plugins/usage_accounting/usage_accounting_tbl.py
- scripts/install/create_tables_cloudsql.py
Added attributes required by Google CloudSQL to the accounting plugin.
> Make accounting plugin work with Google CloudSQL

- engine/src/juliabox/plugins/bucket_gs/impl_gs.py
Went through doumentation [here](https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload#start-resumable) to better implement retries in GCS plugin.  This might fix some sporadic connection errors during push/pull.
I pushed/pulled a 500MB file to see the performance changes in the existing code and this pull request:
| | Existing code | This pull request
--- | --- | ---
| push | 5.67 | 20.69
| pull | 41.31 | 30.46
> Make GCS push/pull more reliable

- engine/src/juliabox/jbox_util.py
Fixed some coding errors in the `retry_on_errors` decorator.
> Fix bugs in retry_on_errors

- docs/Architecture.md
- engine/src/juliabox/cloud/compute.py
- engine/src/juliabox/plugins/compute_ec2/impl_ec2.py
- engine/src/juliabox/plugins/compute_gce/impl_gce.py
- engine/src/juliabox/plugins/compute_singlenode/impl_singlenode.py
Fix a circular dependency issue caused by #409
> Fix circular dependency caused by #409

- engine/src/juliabox/cloud/compute.py
Fix a syntax error in function definition
> Fix a syntax error in function definition

- container/api/Dockerfile
- engine/conf/tornado.conf.tpl
- engine/src/juliabox/api/api_container.py
- engine/src/juliabox/plugins/site_redirect/__init__.py
- engine/src/juliabox/plugins/site_redirect/impl_site_redirect.py
- engine/src/juliabox/plugins/site_redirect/redirect.tpl
- scripts/install/img_create.sh
- fix API containers which were broken after making Julia v0.4 the default
- add a site redirect post-auth plugin which can be used to redirect users to another site.
> fix api and add site redirect plugin

- engine/src/juliabox/db/user_profile.py
Remove invalid SQL indexes from user profile table.
> Remove invalid index

- scripts/install/create_tables_cloudsql.py
> Fix some typos in create_tables_cloudsql.py

- engine/www/ipnbadmin.tpl
Show button instead of link to purge packages directory.
> Change purge link to button

- engine/www/ipnbadmin.tpl
> Changes to package reset section

- container/interactive/IJulia/tutorial/Calling C and Python.ipynb
- container/interactive/IJulia/tutorial/Plotting in Julia.ipynb
Fix deprecation warnings for notebooks in tutorial.
> Fix dep warns in tutorials

- engine/src/juliabox/plugins/auth_github/github_auth.py
Email id is not available via `/user` API call when user has set email id to private.  In this case use `/user/emails` to get the private email id.
> Use the /user/emails API to get private email when public email is not available in GitHub Auth plugin

- engine/src/juliabox/plugins/auth_google/google_auth.py
Perform exponential retry when request for user information fails with 500 error.
> Retry request for user info in google auth when 500 error occurs

- docs/INSTALL.MD
Needed to make the instance load here.
> Add vol_defcfg to config example

- engine/src/juliabox/plugins/auth_google/google_auth.py
Store and check for a secret string in the state parameter.
Related to #455
> Have secret key in state parameter for Google auth

- engine/src/juliabox/plugins/auth_github/github_auth.py
- engine/src/juliabox/plugins/auth_google/google_auth.py
- engine/src/juliabox/plugins/auth_linkedin/linkedin_auth.py
Get the right client IP when using load balancer.
> Fix recording of user ip on login

- webserver/www/assets/js/juliabox.js
Prompt user to save unsaved notebooks after logging in again after session expires or times out.
> Prompt user to save notebooks after session timeout/expiry

- engine/src/juliabox/plugins/email_whitelist/__init__.py
- engine/src/juliabox/plugins/email_whitelist/email_verify.py
- engine/src/juliabox/plugins/email_whitelist/email_verify_tbl.py
- engine/src/juliabox/plugins/email_whitelist/email_whitelist.tpl
- engine/src/juliabox/plugins/email_whitelist/impl_email_whitelist.py
- engine/src/juliabox/plugins/email_whitelist/info.md
- engine/src/juliabox/plugins/email_whitelist/message.tpl
- engine/src/juliabox/plugins/sendmail_smtp/impl_smtp.py
- scripts/install/create_tables_sqlite.py
As discussed in issue #339. For docs, see https://github.com/barche/JuliaBox/blob/master/engine/src/juliabox/plugins/email_whitelist/info.md
> Email whitelisting
